[theme]
base = "light"
primaryColor = "#E86038"
backgroundColor = "#F4F7FC"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
